default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: demoblog
  password: uiop7890

development:
  <<: *default
  database: demo_blog_development

test:
  <<: *default
  database: demo_blog_test

production:
  <<: *default
  database: demo_blog_production
  username: demo_blog
  password: <%= ENV["DEMO_BLOG_DATABASE_PASSWORD"] %>
